import Foundation

// MARK: - RigAndAnimateFlow

/// Orchestrates the multi-step "rig and optionally animate" pipeline for an
/// existing `.model3D` asset.
///
/// Flow:
///   1. Caller supplies the source `.model3D` asset whose `provenance` carries
///      a Meshy `taskId` (persisted by `Meshy3DAssetImporter.makeProvenance`).
///   2. `runRigging(sourceTaskId:sourceAssetName:options:existingAssetNames:onProgress:)`
///      POSTs `/rigging`, polls until `.succeeded`, downloads the rigged GLB
///      (and the bundled basic walking/running clips when requested),
///      builds `.model3D` assets with `isRigged = true`, and returns them
///      together with the rigging task id for chaining.
///   3. The caller (e.g. `RigAndAnimateCoordinator` in `Hype/Views/`) presents
///      `AnimationPickerView` and, if the user picks an action, calls
///      `runAnimation(rigTaskId:actionId:actionName:sourceAssetName:options:existingAssetNames:onProgress:)`.
///   4. `runAnimation` POSTs `/animations`, polls, downloads the animated GLB,
///      builds a `.model3D` asset with `isRigged = true` and
///      `animationActionId = <id>`, and returns it.
///
/// Threading: same contract as `Generate3DJob` — I/O happens on the `client`
/// actor. Progress callbacks fire on whatever executor the caller awaits on.
/// The flow struct itself is `Sendable` with no mutable state.
///
/// Cancellation: the caller holds the outer `Task`; cancelling it while a
/// monitor is running triggers the monitor's `onTermination` path which issues
/// a best-effort DELETE to the Meshy API.
public struct RigAndAnimateFlow: Sendable {

    // MARK: - Options

    /// Options that shape the rigging stage.
    public struct RiggingOptions: Sendable, Equatable {
        /// Character height in meters, passed to Meshy. Default 1.7 m.
        public var heightMeters: Double
        /// Also download the basic walking animation bundled with the rig
        /// (no extra credit cost — Meshy includes it automatically).
        public var alsoBasicWalk: Bool
        /// Also download the basic running animation bundled with the rig.
        public var alsoBasicRun: Bool
        /// Hard wall-clock cap on the rig poll in seconds. Default 1800 (30 min).
        public var hardTimeout: TimeInterval

        public init(
            heightMeters: Double = 1.7,
            alsoBasicWalk: Bool = true,
            alsoBasicRun: Bool = false,
            hardTimeout: TimeInterval = 1800
        ) {
            self.heightMeters = heightMeters
            self.alsoBasicWalk = alsoBasicWalk
            self.alsoBasicRun = alsoBasicRun
            self.hardTimeout = hardTimeout
        }
    }

    /// Options that shape the animation stage.
    public struct AnimationOptions: Sendable, Equatable {
        /// Hard wall-clock cap on the animation poll in seconds. Default 1800.
        public var hardTimeout: TimeInterval

        public init(hardTimeout: TimeInterval = 1800) {
            self.hardTimeout = hardTimeout
        }
    }

    // MARK: - Private state

    private let client: MeshyClient
    private let logger: HypeLogger

    // MARK: - Init

    public init(client: MeshyClient, logger: HypeLogger = .shared) {
        self.client = client
        self.logger = logger
    }

    // MARK: - Public API

    /// Run the rigging stage.
    ///
    /// - Parameters:
    ///   - sourceTaskId: Task id of the source 3D model task. Must be non-empty.
    ///     The source model must have been generated by Meshy (`input_task_id`
    ///     routing — model bytes never leave the user's machine via a third-party URL).
    ///   - sourceAssetName: Display name of the source asset used to derive
    ///     sensible names for the new assets (e.g. "hero" → "hero-rigged.glb").
    ///   - options: Rigging options (height, basic clips, timeout).
    ///   - existingAssetNames: Names already in the repository (for dedup).
    ///   - onProgress: Optional progress callback. Fires on every monitor state change.
    /// - Returns: `(assets, rigTaskId)` — the imported rigged assets (1..3
    ///   entries: rigged GLB plus optional basic walking/running clips) AND the
    ///   Meshy rigging task id so the caller can chain `runAnimation`.
    /// - Throws: `MeshyError` on any pipeline failure.
    public func runRigging(
        sourceTaskId: String,
        sourceAssetName: String,
        options: RiggingOptions,
        existingAssetNames: Set<String>,
        onProgress: Generate3DJob.ProgressHandler? = nil
    ) async throws -> (assets: [Asset], rigTaskId: String) {

        // Step 1: POST /rigging.
        let request = MeshyRiggingRequest(
            inputTaskId: sourceTaskId,
            heightMeters: options.heightMeters
        )
        let rigTaskId = try await client.createRiggingTask(request)

        // Step 2: Build monitor.
        let config = MeshyTaskMonitor.Config(
            pollInterval: 3.0,
            hardTimeout: options.hardTimeout
        )
        let monitor = MeshyTaskMonitor(
            client: client,
            taskId: rigTaskId,
            prompt: "rig: \(sourceAssetName)",
            aiModel: .meshy6,
            requestedFormats: [.glb],
            taskKind: .rigging,
            config: config,
            logger: logger
        )

        // Step 3: Poll until terminal state.
        var taskResult: MeshyTaskResult?
        for await state in await monitor.progress() {
            await onProgress?(state)

            switch state {
            case .succeeded(let result):
                taskResult = result
            case .failed(let error):
                throw error
            case .cancelled:
                throw MeshyError.taskCancelled(taskId: rigTaskId)
            case .pending, .inProgress:
                break
            }

            if taskResult != nil { break }

            if Task.isCancelled {
                await monitor.cancel()
                throw CancellationError()
            }
        }

        guard let result = taskResult else {
            throw MeshyError.taskFailed(taskId: rigTaskId, message: "No result received from rigging monitor.")
        }

        // Step 4: Import downloaded assets.
        let importer = Meshy3DAssetImporter(client: client, logger: logger)
        let assets = try await importer.importRiggingTask(
            result: result,
            sourceAssetName: sourceAssetName,
            existingAssetNames: existingAssetNames,
            sourcePrompt: "rig: \(sourceAssetName)"
        )

        logger.info("runRigging complete: \(assets.count) asset(s), rigTaskId=\(rigTaskId)", source: "Meshy")
        return (assets: assets, rigTaskId: rigTaskId)
    }

    /// Run the animation stage for an already-completed rigging task.
    ///
    /// - Parameters:
    ///   - rigTaskId: The rigging task id produced by `runRigging`.
    ///   - actionId: Numeric action id picked from `MeshyAnimationCatalog`.
    ///   - actionName: Display-friendly action name (used for the new asset's
    ///     file name and provenance.searchQuery).
    ///   - sourceAssetName: For name derivation (same as `runRigging`).
    ///   - options: Animation options (timeout).
    ///   - existingAssetNames: For dedup.
    ///   - onProgress: Optional progress callback.
    /// - Returns: An imported animation asset with `.model3D` kind,
    ///   `isRigged = true`, `animationActionId = actionId.value`.
    /// - Throws: `MeshyError` on any pipeline failure.
    public func runAnimation(
        rigTaskId: String,
        actionId: MeshyActionId,
        actionName: String,
        sourceAssetName: String,
        options: AnimationOptions,
        existingAssetNames: Set<String>,
        onProgress: Generate3DJob.ProgressHandler? = nil
    ) async throws -> Asset {

        // Step 1: POST /animations.
        let request = MeshyAnimationRequest(
            rigTaskId: rigTaskId,
            actionId: actionId
        )
        let animTaskId = try await client.createAnimationTask(request)

        // Step 2: Build monitor.
        let config = MeshyTaskMonitor.Config(
            pollInterval: 3.0,
            hardTimeout: options.hardTimeout
        )
        let monitor = MeshyTaskMonitor(
            client: client,
            taskId: animTaskId,
            prompt: "animate: \(sourceAssetName) \(actionName)",
            aiModel: .meshy6,
            requestedFormats: [.glb],
            taskKind: .animation,
            config: config,
            logger: logger
        )

        // Step 3: Poll until terminal state.
        var taskResult: MeshyTaskResult?
        for await state in await monitor.progress() {
            await onProgress?(state)

            switch state {
            case .succeeded(let result):
                taskResult = result
            case .failed(let error):
                throw error
            case .cancelled:
                throw MeshyError.taskCancelled(taskId: animTaskId)
            case .pending, .inProgress:
                break
            }

            if taskResult != nil { break }

            if Task.isCancelled {
                await monitor.cancel()
                throw CancellationError()
            }
        }

        guard let result = taskResult else {
            throw MeshyError.taskFailed(taskId: animTaskId, message: "No result received from animation monitor.")
        }

        // Step 4: Import downloaded asset.
        let importer = Meshy3DAssetImporter(client: client, logger: logger)
        let asset = try await importer.importAnimationTask(
            result: result,
            sourceAssetName: sourceAssetName,
            actionId: actionId,
            actionName: actionName,
            existingAssetNames: existingAssetNames,
            sourcePrompt: "animate: \(sourceAssetName) \(actionName)"
        )

        logger.info(
            "runAnimation complete: asset=\(asset.name) action=\(actionId.value) animTaskId=\(animTaskId)",
            source: "Meshy"
        )
        return asset
    }
}
