import SwiftUI
import HypeCore

// MARK: - RemeshAndRetextureCoordinator

/// Coordinator view for the Remesh or Retexture flows.
///
/// Presented as a sheet from `AssetRepositoryView` when the user picks
/// "Remesh\u{2026}" or "Retexture\u{2026}" on a `model3D` asset that was
/// generated by Meshy. One coordinator handles both modes because they share
/// the same preflight validation, gate check, and completion handling.
///
/// Phase state machine:
///   `.configuring`      — parameter input UI for the chosen mode.
///   `.running(percent)` — flow is in flight.
///   `.done`             — success; the new asset is in the repository.
///   `.error(MeshyError)` — terminal failure.
///
/// Security:
/// - `flowTask?.cancel()` is called on sheet disappear, cancelling
///   in-flight network requests.
/// - Keychain reads are done via `Task.detached(priority: .userInitiated)`
///   to avoid synchronous SecItem calls on the main thread (security M3).
struct RemeshAndRetextureCoordinator: View {

    // MARK: - Mode

    enum Mode: Equatable {
        case remesh
        case retexture
    }

    // MARK: - Phase

    enum Phase: Equatable {
        case configuring
        case running(percent: Int)
        case done
        case error(MeshyError)
    }

    // MARK: - Inputs

    @Binding var document: HypeDocumentWrapper
    let sourceAsset: Asset
    let mode: Mode
    var onDismiss: () -> Void
    var onAssetImported: ((UUID) -> Void)?

    // MARK: - State

    @State private var phase: Phase = .configuring
    @State private var flowTask: Task<Void, Never>?
    @State private var meshyKeyIsSet: Bool = false
    /// Imported asset name, shown in the done view.
    @State private var importedAssetName: String = ""

    // Remesh parameters
    @State private var targetPolycount: Int = 30_000
    @State private var topology: String = "triangle"

    // Retexture parameters
    @State private var stylePrompt: String = ""
    @State private var enablePbr: Bool = false
    @State private var hdTexture: Bool = false

    // MARK: - Body

    var body: some View {
        VStack(spacing: 0) {

            // Header
            HStack {
                Text(mode == .remesh ? "Remesh Model" : "Retexture Model")
                    .font(.headline)
                Spacer()
                Text(sourceAsset.name)
                    .font(.system(size: 11))
                    .foregroundColor(.secondary)
                    .lineLimit(1)
            }
            .padding()

            Divider()

            // Main content region
            Group {
                switch phase {
                case .configuring:
                    configuringView

                case .running(let percent):
                    progressView(percent: percent)

                case .done:
                    doneView

                case .error(let err):
                    errorView(err)
                }
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)

            Divider()
            footerButtons
        }
        .frame(width: 480, height: 380)
        .onAppear {
            // Probe Keychain off the main thread (security M3).
            Task.detached(priority: .userInitiated) {
                let keyIsSet = KeychainStore.hasSecret(account: KeychainStore.meshyAPIKeyAccount)
                await MainActor.run {
                    meshyKeyIsSet = keyIsSet
                }
            }
        }
        .onDisappear {
            flowTask?.cancel()
        }
    }

    // MARK: - Configuring view

    @ViewBuilder
    private var configuringView: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                if mode == .remesh {
                    remeshFields
                } else {
                    retextureFields
                }
            }
            .padding()
        }
    }

    @ViewBuilder
    private var remeshFields: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Target Polygon Count").font(.system(size: 12, weight: .medium))
            HStack {
                Slider(
                    value: Binding(
                        get: { Double(targetPolycount) },
                        set: { targetPolycount = max(100, min(300_000, Int($0))) }
                    ),
                    in: 100...300_000,
                    step: 100
                )
                Text("\(targetPolycount.formatted())")
                    .font(.system(size: 11, design: .monospaced))
                    .frame(width: 70, alignment: .trailing)
            }
            Text("Range: 100 – 300,000")
                .font(.system(size: 10))
                .foregroundColor(.secondary)
        }

        VStack(alignment: .leading, spacing: 8) {
            Text("Topology").font(.system(size: 12, weight: .medium))
            Picker("", selection: $topology) {
                Text("Triangle").tag("triangle")
                Text("Quad").tag("quad")
            }
            .pickerStyle(.segmented)
            .fixedSize()
        }

        if !meshyKeyIsSet {
            keyMissingHint
        }
    }

    @ViewBuilder
    private var retextureFields: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Style Prompt").font(.system(size: 12, weight: .medium))
            TextEditor(text: $stylePrompt)
                .font(.system(size: 12))
                .frame(height: 72)
                .overlay(RoundedRectangle(cornerRadius: 4).stroke(Color.gray.opacity(0.3)))
            if stylePrompt.count > 600 {
                Text("Prompt will be truncated to 600 characters.")
                    .font(.system(size: 10))
                    .foregroundColor(.orange)
            } else {
                Text("\(stylePrompt.count) / 600")
                    .font(.system(size: 10))
                    .foregroundColor(.secondary)
            }
        }

        Toggle("Generate PBR maps", isOn: $enablePbr)
            .font(.system(size: 12))

        Toggle("4K base color (HD texture)", isOn: $hdTexture)
            .font(.system(size: 12))

        if !meshyKeyIsSet {
            keyMissingHint
        }
    }

    @ViewBuilder
    private var keyMissingHint: some View {
        HStack(spacing: 6) {
            Image(systemName: "exclamationmark.triangle")
                .foregroundColor(.orange)
                .font(.system(size: 11))
            Text("Meshy API key required. Set it in Preferences \u{2192} Meshy.ai.")
                .font(.system(size: 10))
                .foregroundColor(.secondary)
        }
    }

    // MARK: - Progress view

    @ViewBuilder
    private func progressView(percent: Int) -> some View {
        VStack(spacing: 20) {
            Spacer()
            Image(systemName: mode == .remesh ? "cylinder.split.1x2" : "paintbrush.pointed")
                .font(.system(size: 36))
                .foregroundColor(.accentColor)
            Text(percent == 0
                 ? (mode == .remesh ? "Submitting remesh request\u{2026}" : "Submitting retexture request\u{2026}")
                 : (mode == .remesh ? "Remeshing\u{2026} \(percent)%" : "Retexturing\u{2026} \(percent)%"))
                .font(.system(size: 13))
            ProgressView(value: Double(percent), total: 100)
                .progressViewStyle(.linear)
                .frame(width: 280)
            Text("This may take several minutes.")
                .font(.system(size: 11))
                .foregroundColor(.secondary)
            Spacer()
        }
        .padding(.horizontal, 40)
    }

    // MARK: - Done view

    @ViewBuilder
    private var doneView: some View {
        VStack(spacing: 16) {
            Spacer()
            Image(systemName: "checkmark.circle.fill")
                .font(.system(size: 36))
                .foregroundColor(.green)
            Text("Asset added to the Asset Repository.")
                .font(.system(size: 13))
                .multilineTextAlignment(.center)
            if !importedAssetName.isEmpty {
                Text(importedAssetName)
                    .font(.system(size: 11, design: .monospaced))
                    .foregroundColor(.secondary)
            }
            Text("The imported model is embedded in this stack and autosaved.")
                .font(.system(size: 11))
                .foregroundColor(.secondary)
            Spacer()
        }
        .padding(.horizontal, 40)
    }

    // MARK: - Error view

    @ViewBuilder
    private func errorView(_ error: MeshyError) -> some View {
        VStack(spacing: 16) {
            Spacer()
            Image(systemName: "exclamationmark.triangle")
                .font(.system(size: 36))
                .foregroundColor(.red)
            Text(mode == .remesh ? "Remesh failed" : "Retexture failed")
                .font(.headline)
            Text(error.errorDescription ?? "An unexpected error occurred.")
                .font(.system(size: 12))
                .foregroundColor(.secondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal)
            Button("Retry") {
                phase = .configuring
            }
            .buttonStyle(.bordered)
            Spacer()
        }
        .padding(.horizontal, 40)
    }

    // MARK: - Footer buttons

    @ViewBuilder
    private var footerButtons: some View {
        HStack {
            Button(isDone ? "Close" : "Cancel") {
                cancelAndDismiss()
            }
            Spacer()
            if case .configuring = phase {
                Button(mode == .remesh ? "Remesh" : "Retexture") {
                    startFlow()
                }
                .buttonStyle(.borderedProminent)
                .disabled(!canStart)
            }
        }
        .padding()
    }

    private var isDone: Bool {
        if case .done = phase { return true }
        if case .error = phase { return true }
        return false
    }

    private var canStart: Bool {
        if !meshyKeyIsSet { return false }
        if mode == .retexture && stylePrompt.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return false
        }
        return true
    }

    // MARK: - Flow entry

    private func startFlow() {
        phase = .running(percent: 0)
        flowTask = Task {
            await runFlow()
        }
    }

    // MARK: - Main async flow

    @MainActor
    private func runFlow() async {
        // Preflight: source must have a Meshy task id.
        guard let provenance = sourceAsset.provenance,
              !provenance.attribution.taskId.isEmpty,
              provenance.attribution.providerIdentifier == "meshy"
        else {
            phase = .error(.validationFailed(
                field: "sourceAsset",
                reason: "This model wasn't generated by Meshy. Remesh and retexture require a Meshy-generated source asset."
            ))
            return
        }
        let sourceTaskId = provenance.attribution.taskId
        let sourcePrompt = provenance.searchQuery

        // Fetch API key off-main (security M3).
        let apiKey: String
        do {
            apiKey = try await Task.detached(priority: .userInitiated) {
                try KeychainStore.getSecret(account: KeychainStore.meshyAPIKeyAccount)
            }.value
        } catch {
            phase = .error(.noAPIKey)
            return
        }

        let client = MeshyAIClient(apiKey: apiKey)
        let flow = RemeshAndRetextureFlow(client: client)
        let existingNames = Set(document.document.assetRepository.assets.map(\.name))

        do {
            let asset: Asset
            switch mode {
            case .remesh:
                let options = RemeshAndRetextureFlow.RemeshOptions(
                    targetPolycount: targetPolycount,
                    topology: topology
                )
                asset = try await flow.runRemesh(
                    sourceTaskId: sourceTaskId,
                    sourceAssetName: sourceAsset.name,
                    sourcePrompt: sourcePrompt,
                    options: options,
                    existingAssetNames: existingNames,
                    onProgress: { [self] state in
                        await MainActor.run {
                            switch state {
                            case .pending:
                                phase = .running(percent: 0)
                            case .inProgress(let pct):
                                phase = .running(percent: pct)
                            case .succeeded, .failed, .cancelled:
                                break
                            }
                        }
                    }
                )
            case .retexture:
                let options = RemeshAndRetextureFlow.RetextureOptions(
                    enablePbr: enablePbr,
                    hdTexture: hdTexture
                )
                asset = try await flow.runRetexture(
                    sourceTaskId: sourceTaskId,
                    sourceAssetName: sourceAsset.name,
                    sourcePrompt: sourcePrompt,
                    newStylePrompt: stylePrompt,
                    options: options,
                    existingAssetNames: existingNames,
                    onProgress: { [self] state in
                        await MainActor.run {
                            switch state {
                            case .pending:
                                phase = .running(percent: 0)
                            case .inProgress(let pct):
                                phase = .running(percent: pct)
                            case .succeeded, .failed, .cancelled:
                                break
                            }
                        }
                    }
                )
            }

            document.document.assetRepository.addAsset(asset)
            importedAssetName = asset.name
            onAssetImported?(asset.id)
            phase = .done
            HypeDocumentMutationCoordinator.shared.flushAllAutosaves()

        } catch is CancellationError {
            return
        } catch let err as MeshyError {
            phase = .error(err)
        } catch {
            phase = .error(.networkError)
        }
    }

    // MARK: - Cancel helper

    private func cancelAndDismiss() {
        flowTask?.cancel()
        onDismiss()
    }
}
